export const JokeCategory = {
  PUN: "Pun",
  ONE_LINER: "One-liner",
  KNOCK_KNOCK: "Knock-knock",
  SARCASTIC: "Sarcastic",
  DRAK: "Dark",
  BLONDE: "Blonde",
  CLEAN: "Clean",
  DIRTY: "Dirty",
  TECH: "Tech",
  POLITICAL: "Political",
  ANIMAL: "Animal",
  INSULT: "Insult",
  RIDDLE: "Riddle",
  OTHER: "Other",
};
